name: Build Soroban Contract
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust wasm target
        run: rustup target add wasm32-unknown-unknown

      - name: Install Stellar CLI
        run: cargo install --locked stellar-cli

      - name: Build contract
        run: stellar contract build

      - name: Upload WASM
        uses: actions/upload-artifact@v4
        with:
          name: barangay_pass_wasm
          path: target/wasm32v1-none/release/barangay_pass.wasm
